import Head from "next/head";
import Header from "../components/Header";
import "../styles/globals.css";

function MyApp({ Component, pageProps }) {
  return (
    <div className="bg-white">
      <Head>
        <title>BlexZET | Indian Blog Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="body">
        <Header />
        <div className="mainPostSection">
          <Component {...pageProps} />
        </div>
        <div className="rightSideSection"></div>
      </main>
    </div>
  );
}

export default MyApp;
